# Generated by Django 5.0.6 on 2024-06-15 12:01

import django.core.validators
import src.base.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Поддерживается формат: jpg, jpeg, png', null=True, upload_to='oauth/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), src.base.services.validate_size_image], verbose_name='Avatar'),
        ),
    ]
