# Generated by Django 5.0.6 on 2024-06-16 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_alter_userssociallink_telegram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
