# Generated by Django 5.0.6 on 2024-06-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_alter_userssociallink_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userssociallink',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='userssociallink',
            name='vk_link',
        ),
        migrations.RemoveField(
            model_name='userssociallink',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='userssociallink',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ссылка на соц.сети'),
        ),
    ]
