# Generated by Django 5.0.6 on 2024-06-17 16:56

import django.core.validators
import src.base.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0009_remove_userssociallink_telegram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Поддерживается формат: jpg, jpeg, png', null=True, upload_to=src.base.services.get_patch_upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), src.base.services.validate_size_image], verbose_name='Avatar'),
        ),
    ]
